### ISSUE TITLE
bug of incorrect "発表状況"

### ISSUE THREAD

**Issue by fenixli** [AllystarTech/qzss-l1s-mtdec#1]
Wrong implementation of get_mt43_weather_Ar(), please see the patch below.

```
hli@SCS-Linux-Server:~/gnss/2GQ/qzss-l1s-mtdec$ git show 24ef89e36eb12d27e6ea60024f37e616d963ccda
commit 24ef89e36eb12d27e6ea60024f37e616d963ccda (HEAD -> fix_bug_mt43)
Author: hli <hui.li@murata.com>
Date:   Wed Jun 19 13:18:15 2024 +0800

    Fix the bug of incorrect "発表状況"

diff --git a/MT43_Match_Table.py b/MT43_Match_Table.py
index 98dc750..6e71655 100644
--- a/MT43_Match_Table.py
+++ b/MT43_Match_Table.py
@@ -2964,7 +2964,7 @@ matchtable_mt43_weather_Ar = { #39
 }
 
 def get_mt43_weather_Ar(Ar):
-    Ar_dec = matchtable_mt43_weather_Ww.get(Ar, "発表状況(コード番号：N)")
+    Ar_dec = matchtable_mt43_weather_Ar.get(Ar, "発表状況(コード番号：N)")
     return Ar_dec
 
 matchtable_mt43_weather_Ww = { #40
```

**Comment by fenixli** [comment]
[0001-Fix-the-bug-of-incorrect.patch](https://github.com/user-attachments/files/15896091/0001-Fix-the-bug-of-incorrect.patch)

**Comment by cherry-chung** [comment]
> Wrong implementation of get_mt43_weather_Ar(), please see the patch below.
> 
> ```
> hli@SCS-Linux-Server:~/gnss/2GQ/qzss-l1s-mtdec$ git show 24ef89e36eb12d27e6ea60024f37e616d963ccda
> commit 24ef89e36eb12d27e6ea60024f37e616d963ccda (HEAD -> fix_bug_mt43)
> Author: hli <hui.li@murata.com>
> Date:   Wed Jun 19 13:18:15 2024 +0800
> 
>     Fix the bug of incorrect "発表状況"
> 
> diff --git a/MT43_Match_Table.py b/MT43_Match_Table.py
> index 98dc750..6e71655 100644
> --- a/MT43_Match_Table.py
> +++ b/MT43_Match_Table.py
> @@ -2964,7 +2964,7 @@ matchtable_mt43_weather_Ar = { #39
>  }
>  
>  def get_mt43_weather_Ar(Ar):
> -    Ar_dec = matchtable_mt43_weather_Ww.get(Ar, "発表状況(コード番号：N)")
> +    Ar_dec = matchtable_mt43_weather_Ar.get(Ar, "発表状況(コード番号：N)")
>      return Ar_dec
>  
>  matchtable_mt43_weather_Ww = { #40
> ```

Thanks for reporting the issue. I have corrected this bug to the latest codes.
